---
application:
  name: "nodedemo"
  project: "nodedemo"
  organization: "QoveryCommunity"
  port: 8080
databases:
- type: "MONGODB"
  name: "dbdemo"
  version: "4.4"
routers:
- name: "main-nodedemo"
  routes:
  - application_name: "nodedemo"
    paths:
    - "/*"
